# Production Docker Compose file

version: '3.8'

services:
 
    backend:
        container_name: dietideals24-backend
        build:
            context: ./Server/backend/
            dockerfile: .dockerfiles/prod-Dockerfile
        depends_on:
            - database
        restart: unless-stopped
        ports:
            - 54321:8080 # Mappa la porta 8080 del container con 54321 nell'host (http://localhost:54321/ ci farà accedere all'app)
        networks:
            - backendNetwork

    database:
        container_name: dietideals24-postgresDB
        image: postgres # Immagine di Postgres già pronta
        restart: unless-stopped
        secrets:
            - databasePassword
        environment:
            - POSTGRES_DB=example
            - POSTGRES_PASSWORD_FILE=/run/secrets/databasePassword
        volumes:
            - ./Server/database/databaseData:/var/lib/postgresql/data
        ports:
            - 5432:5432
        networks:
            - backendNetwork

volumes:
    databaseData:

secrets:
    databasePassword:
        file: ./Server/database/password.txt

networks:
    backendNetwork: