# Development Docker Compose file for backend

version: '3.8'

services:

    # Update this to the name of the service you want to work with in your docker-compose.yml file
    backend: # Note: we only override the backend service, we will let frontend pull from  a production-ready image. You can always override this if you prefer to keep frontend deployed from your local Dockerfile
        container_name: dietideals24-backend-dev

        # Uncomment if you want to override the service's Dockerfile to one in the .devcontainer 
        # folder. Note that the path of the Dockerfile and context is relative to the *primary* 
        # docker-compose.yml file (the first in the devcontainer.json "dockerComposeFile"
        # array). The sample below assumes your primary file is in the root of your project.
        build: # override the backend configs to build from our src code folder's Dockerfile
            context: ./Server/backend/
            dockerfile: .dockerfiles/dev-Dockerfile

        # Update this to wherever you want VS Code to mount the folder of your project
        volumes:
            - .:/workspaces:cached  # mount our local backend folder to the dev container as its workspace folder

        # Uncomment the next four lines if you will use a ptrace-based debugger like C++, Go, and Rust.
        # cap_add:
        #   - SYS_PTRACE
        # security_opt:
        #   - seccomp:unconfined
        
        # Overrides default command so things don't shut down after the process ends.
        command: /bin/sh -c "while sleep 1000; do :; done"