package com.iasdietideals24.dietideals24.utilities.enumerations

enum class CategoriaAsta {
    BOOKS,
    COMICS_AND_MANGAS,
    MUSIC,
    MOVIES_AND_TV_SHOWS,
    VIDEOGAMES_AND_CONSOLES,
    ELECTRONICS,
    FOODS_AND_DRINKS,
    PETS_SUPPLIES,
    BODYCARE_AND_BEAUTY,
    SPORTS_AND_HOBBIES,
    CLOTHINGS_AND_WEARABLES,
    HOME_AND_FURNITURES,
    VEHICLES,
    OTHER
}